### ISSUE TITLE
Adjacent vertices

### ISSUE THREAD

**Issue by andynkili** [csbl-usp/fcoex#16]
I am interested in a specific gene in the module and its most correlated neighbors.
I would like to know if there is a way of getting all adjacent vertices for a particular gene in a module?
I check in the object but the '**fc@coex_network_plot$SLC1A2$data**' seems to not contain that information.

Moreover how are defined the degree in that dataframe? 
Because when I plot the related network the degrees don't match the number of edge connecting vertices.

Best,
Andy

**Comment by lubianat** [comment]
Hello, Andy, thank you for using fcoex. 

`fc@coex_network_plot$SLC1A2$data` contains (if I remember correctly) the data about the ggplot2 plot. 

Degrees are defined via the fcoex algorithm; it is roughly the number of genes correlated to the gene of interest that are above a certain threshold. This threshold is different for each gene. 

It might be that the plot is not rendering some o the edges. Maybe increasing the size of the plotting device will help. 

As per the adjanced edges, the graph is availble in  fc@adjacency_trimmed .

See https://github.com/csbl-usp/fcoex/blob/7edb01c21a3fdf08fbdd1ca452af551e8ff37966/R/fcoex.R#L212 


I might take a few days to reply, but if you have any further questions just let me know!
