### ISSUE TITLE
fcoex vs CEMiTool?

### ISSUE THREAD

**Issue by mr-september** [csbl-usp/fcoex#4]
Hi Authors, couldn't seem to find any article publication introducing fcoex, and the Readme is rather brief.

Would just like to know what are the novelties or shortcomings addressed by fcoex over CEMiTools? Or any other pros/cons users should be aware of?

Just a quick text summary would be appreciated. Thanks!

**Comment by lubianat** [comment]
Hello @mr-september , thank you for the question! 

They are based on different mathematics and (generally) CEMiTool modules are larger than fcoex modules. 

The fcoex is a more experimental approach, built for single-cell RNA-seq specifically.
We are still writing the publication, it was stalled for a while (too many projects!) .

CEMiTool is a more robust package, and it is based on WGCNA, which is a well established gold standard. 

If you are dealing with bulk sequencing, CEMiTool will likely be best. 

If you are dealing with single-cell, I'd say to try CEMiTool and see if it fits your needs. Some assumptions for bulk RNA-seq do not always hold, so it might not give you good results (or no results at all). 

If CEMiTool is not enough, then fcoex might be for you. 

One other option is to use Monocle3 (https://cole-trapnell-lab.github.io/monocle3/docs/differential/#gene-modules), which has also a good approach for single-cell modules. 

What is your use case? I'd be happy to give more detailed feedback.

**Comment by mr-september** [comment]
Hi @lubianat , thank you for the explanation!

I previously did not notice that CEMiTool was focused on bulk datasets.

Since I am working single-cell RNA datasets, it looks like fcoex is the default winner for my use case?

Would you be able to very briefly describe how you've adapted CEMiTool's framework to be more suitable for single-cell datasets? Just general concepts would do :)

**Comment by lubianat** [comment]
It probably depends on your question, but fcoex should be a good starting point. 

fcoex uses CEMiTools visualizations, but the algorithm behind building the modules is different. 

Generally, CEMiTool filters for genes with high variance, creates a correlation matrix, selects a minimum correlation for building the network and finds the modules on this matrix using WGCNA. 

fcoex uses a binarized matrix (on/off), selects genes that correlate with cluster assignments (so it is partially supervised) and then builds a correlation matrix using a different method (called "symmetrical uncertainty). The fcoex modules are a bit more experimental, and more fuzzy (more overlap between the genes in different modules)

**Comment by mr-september** [comment]
Thank you for the explanation again, @lubianat.

>selects genes that correlate with cluster assignments

This probably explains why genes selected by fcoex was entirely a subset of marker genes (of various forms, as found by DEsingle).

Really looking forward to your full article, and wishing you all the best!
