### ISSUE TITLE
Significance of Module Name and Network Edge distances?

### ISSUE THREAD

**Issue by mr-september** [csbl-usp/fcoex#6]
Hi, I'm sorry to be bothering again.

I realise you'll probably have these details in your final publication, but I am keen to already be using this tool. I have 2 further questions:

1. I was just wondering how Genes are selected to be the "Names" of each module, is it something like centrality? Or some other metric?

2. Is there any significance in the distance between nodes (length of edges)? I noticed some plots have one tight cluster with surrounding sparse nodes. Or is this purely for aesthetics?

**Comment by lubianat** [comment]
@mr-september no bother, they are both very good questions. 

1. The name of each module is selected by the "predominant correlation", which is, roughly, the gene that best separates the single-cell clusters. It means that no other gene in module "A" is more correlated to "A" than "A" is to the clusters.  It is a heuristic to try to find a biologically-relevant name. 

2. That is purely aesthetics. The nodes are laid out using an algorithm called "Fruchterman-Reingold" that is  aesthetically pleasing. That is coded in the snippet:

`   plotcord <-
    data.frame(sna::gplot.layout.fruchtermanreingold(m, NULL))`
    
 at https://github.com/csbl-usp/fcoex/blob/master/R/visualization.R . 
 
 I'll speed up the preprint (it has been stalled over the past year with the pandemic and so on), and I'll let you know ASAP :)

**Comment by mr-september** [comment]
Thank you! Great explanations. Hope things are getting better there :)
